loadBalancerIP: 35.198.153.128
replicas: 1
service:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "production-ingress"
logLevel: info # debug
ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  challengeType: http-01 # tls-alpn-01
  email: Michael@Sprauer.net
  logging: true
  staging: false
  persistence:
    enabled: true
rbac:
  enabled: true
deployment:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
metrics:
  prometheus:
    enabled: true