apiVersion: apps/v1
kind: Deployment
metadata:
  name: imis-server
  labels:
    app: imis-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imis-server
  template:
    metadata:
      labels:
        app: imis-server
    spec:
      containers:
      - name: imis-server
        image: server-image
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://localhost:5432/postgres
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        volumeMounts:
        - name: cloudstore-service-account
          mountPath: /usr/local/cloud-store
          readOnly: true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                  "-instances=onyx-yeti-271818:europe-west3:challenge-11=tcp:5432",
          # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
          # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
          # "-ip_address_types=PRIVATE",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql
        - name: cloudstore-service-account
          secret:
            secretName: cloudstore