FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install
COPY . .
ARG SENTRY_FRONTEND_DSN
ARG DEPLOY_ENV
ENV SENTRY_FRONTEND_DSN $SENTRY_FRONTEND_DSN
ENV DEPLOY_ENV $DEPLOY_ENV
RUN yarn run build

# production stage
FROM nginx:stable-alpine as production-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY .nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]