version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: imis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imis
    ports:
        - "5432:5432"
    restart: unless-stopped

  client:
    build:
      context: client
      dockerfile: Dockerfile.prod
    ports:
    - "8081:8080"

  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/imis
    ports:
    - "8080:8080"
