version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: imis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imis
    ports:
        - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  core:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/imis
    build: .
    networks:
      - postgres
    ports:
      - "80:4000"

  web:
    build: .
    networks:
      - postgres
    entrypoint: ["sh", "/app/gradlew", "serve"]
    ports:
      - "8080:8080"


networks:
  postgres:
    driver: bridge
