version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: imis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imis
    ports:
    - "5432:5432"
    restart: unless-stopped

#  client:
#    build:
#      context: client
#      dockerfile: Dockerfile
#    ports:
#    - "8080:8080"
#    depends_on:
#    - server # for generating models from swagger api

  server:
    image: gcr.io/onyx-yeti-271818/imis-fullstack
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/imis
    ports:
    - "80:80"
    depends_on:
    - postgres
