FROM gradle:6.2.2-jdk11 AS build
COPY --chown=gradle:gradle . /src
WORKDIR /src
RUN gradle -x :client:assemble assemble --no-daemon

FROM openjdk:11-jre-slim
COPY --from=build /src/server/build/libs/imis.jar /app.jar
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
ENTRYPOINT ["java", "-Xmx64m", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar" ]