apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: imis
  name: imis
resources:
- .k8s/deployment.yaml
images:
- name: imis
  newName: gcr.io/onyx-yeti-271818/imis
  newTag: latest
