apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: imis
  name: imis
resources:
- .k8s/deployment-server.yaml
- .k8s/deployment-client.yaml
- .k8s/services.yml
- .k8s/ingress.yml
images:
- name: client-image
  newName: gcr.io/onyx-yeti-271818/imis-client
  newTag: latest
- name: server-image
  newName: gcr.io/onyx-yeti-271818/imis-server
  newTag: latest
secretGenerator:
- literals:
  - password=${POSTGRES_PASSWORD}
  name: postgress
  type: Opaque
