apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imis.client.fullname" . }}
  labels:
  {{- include "imis.client.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "imis.client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "imis.client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: imis-client
        image: "{{- .Values.image.repository}}/imis-client:{{- .Values.gitSha }}"
        env:
        - name: CLUSTER_ENVIRONMENT
          value: {{ .Values.env }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: imis-sentry
              key: frontend
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1