apiVersion: v1
kind: Secret
metadata:
  name: cloudsql
  labels:
  {{- include "imis.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ (.Files.Get (.Values.secrets.cloudSql)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudstore
  labels:
  {{- include "imis.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ (.Files.Get (.Values.secrets.cloudStore)) }}
---
{{ if ne .Values.secrets.postgres ""}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
  {{- include "imis.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.postgres }}
{{ end }}
