apiVersion: v1
kind: Service
metadata:
  name: "{{- include "imis.fullname" . }}"
  labels:
    {{- include "imis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "imis.selectorLabels" . | nindent 4 }}