spring:
  profiles:
    active: development
  cloud:
    gcp:
      storage:
        enabled: false
      sql:
        enabled: false
---
spring:
  profiles: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imis
    username: imis
    password: password
    initialization-mode: always
    platform: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        search:
          default:
            directory_provider: filesystem
            indexBase: build/data/search
server:
  port: 80
---
feature:
  testdata: true
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql:///postgres?cloudSqlInstance=onyx-yeti-271818:europe-west3:challenge-11&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: /data
  cloud:
    gcp:
      project-id: onyx-yeti-271818
      sql:
        database-name: postgres
        instance-connection-name: onyx-yeti-271818:europe-west3:challenge-11
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
---
feature:
  testdata: true
spring:
  profiles: staging
  datasource:
    initialization-mode: always
    url: jdbc:postgresql:///staging?cloudSqlInstance=onyx-yeti-271818:europe-west3:challenge-11&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres
---
feature:
  testdata: true
spring:
  profiles: pull-request
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql:///pr?cloudSqlInstance=onyx-yeti-271818:europe-west3:challenge-11&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: /data
  cloud:
    gcp:
      project-id: onyx-yeti-271818
      sql:
        database-name: pr
        instance-connection-name: onyx-yeti-271818:europe-west3:challenge-11
        enabled: true
---
feature:
  testdata: true
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: build/data/search
---
spring:
  profiles: swagger-export
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  main:
    banner-mode: off
management:
  health:
    db:
      enabled: false