spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    gcp:
      storage:
        enabled: false
      sql:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imis
    username: imis
    password: password
    initialization-mode: always
    platform: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        search:
          default:
            directory_provider: filesystem
            indexBase: build/data/search
server:
  port: 80
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql:///staging/pull_requests?cloudSqlInstance=onyx-yeti-271818:europe-west3:challenge-11&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: /data
  cloud:
    gcp:
      project-id: onyx-yeti-271818
      sql:
        database-name: pull_requests
        instance-connection-name: onyx-yeti-271818:europe-west3:challenge-11
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    gcp:
      storage:
        enabled: false
      sql:
        enabled: false
