spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    gcp:
      storage:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imis
    username: imis
    password: password
    initialization-mode: always
    platform: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 80
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql:localhost:5432
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    gcp:
      credentials:
        location: file:/usr/local/cloud-store/credentials.json
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  server:
    port: 8081
---
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
