package de.coronavirus.imis.domain;

public enum EventType {
    SUSPECTED,
    TEST_SUBMITTED,
    TEST_FINISHED_POSITIVE,
    TEST_FINISHED_NEGATIVE,
    TEST_FINISHED_RECOVERED,
    TEST_FINISHED_NOT_RECOVERED,
    PATIENT_DEAD
}
