package de.coronavirus.imis.domain;

public enum EventType {
	REGISTERED,
	SUSPECTED,
	ORDER_TEST,
	SCHEDULED_FOR_TESTING,
	TEST_SUBMITTED,
	TEST_FINISHED_POSITIVE,
	TEST_FINISHED_NEGATIVE,
	PATIENT_DEAD,
	DOCTORS_VISIT,
	QUARANTINE_SELECTED, /* Vorgemerkt */
	QUARANTINE_MANDATED,
	QUARANTINE_RELEASED,
	QUARANTINE_PROFESSIONBAN_RELEASED,
	HOSPITALIZATION_MANDATED,
	HOSPITALIZATION_RELEASED,
	CASE_DATA_UPDATED,
}
