name: CI

on:
  push:
    branches:
    - feature/*
    - master
    - dev
    - pilot
  pull_request:
    branches:
    - master
    - dev
    - pilot

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    - uses: actions/checkout@v2

    # begin caching
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(./gradlew yarn_cache_dir -q --console=plain)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    # end caching

    - run: |
        gradle test -x lint
  run-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - if: ${{ github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository ) }}
      uses: hallee/eslint-action@1.0.3
      with:
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        source-root: "client"